
version: "3.8"

services:
  # mysql:
  #   image: mysql:8.0
  #   networks:
  #     - network   
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_USER: springuser
  #     MYSQL_PASSWORD: ThePassword
  #     MYSQL_DATABASE: cmpe172
  #   restart: always
  
  # books:
  #   image: rheadash/spring-books:v1
  #   depends_on:
  #   - mysql    
  #   volumes:
  #     - /tmp:/tmp
  #   networks:
  #     - network   
  #   ports:
  #     - 8080    
  #   environment:
  #     MYSQL_HOST: "mysql"
  #   restart: always 
  # payments:
  #   image: rheadash/spring-payments:v1
  #   depends_on:
  #   - mysql    
  #   volumes:
  #     - /tmp:/tmp
  #   networks:
  #     - network   
  #   ports:
  #     - 8081    
  #   environment:
  #     MYSQL_HOST: "mysql"
  #   restart: always
  frontend:
    build: frontend
    depends_on:
    - users
    networks:
      - network
    ports:
      - 8080:8080
    restart: always
  users:
    #image: backend
    build: spring-users
    depends_on:
    - mysql    
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8082:8082
    #environment:
    #  MYSQL_HOST: "mysql"
    restart: always       
  # lb:
  #   image: eeacms/haproxy
  #   depends_on:
  #   - b
  #   ports:
  #   - "80:5000"
  #   - "1936:1936"
  #   environment:
  #     BACKENDS: "gumball"
  #     BACKENDS_PORT: "8080"
  #     DNS_ENABLED: "true"
  #     COOKIES_ENABLED: "false"
  #     LOG_LEVEL: "info"
  #   networks:
  #     - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
