
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    networks:
      - network   
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_DATABASE: cmpe172
      MYSQL_ROOT_PASSWORD: cmpe172
    restart: always

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
