apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  01.sql: |
    CREATE USER 'cmpe172'@'%' IDENTIFIED BY 'Abc@123$';
    GRANT ALL ON `cmpe172`.* to 'cmpe172'@'%';
    CREATE DATABASE IF NOT EXISTS `springpayments`;
    GRANT ALL ON `springpayments`.* TO 'cmpe172'@'%';
    CREATE DATABASE IF NOT EXISTS `springusers`;
    GRANT ALL ON `springusers`.* TO 'cmpe172'@'%';
    CREATE DATABASE IF NOT EXISTS `springbooks`;
    GRANT ALL ON `springbooks`.* TO 'cmpe172'@'%';

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql
    spec:
      volumes:
        - name: mysql-init-sql
          configMap:
            name: mysql-init-sql
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: cmpe172
        - name: MYSQL_PASSWORD
          value: ThePassword
        - name: MYSQL_ROOT_PASSWORD
          value: cmpe172
        - name: MYSQL_USER
          value: springuser
        image: mysql:8.0
        name: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-init-sql
            mountPath: /docker-entrypoint-initdb.d
        resources: {}
      restartPolicy: Always
status: {}
