apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: payments
  name: payments
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payments
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/cmpe172
        image: rheadash/spring-payments:v1
        name: payments
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: payments-claim0
      restartPolicy: Always
      volumes:
      - name: payments-claim0
        persistentVolumeClaim:
          claimName: payments-claim0
status: {}
