apiVersion: v1
kind: Service
metadata:
  name: spring-users-lb
spec:
  type: LoadBalancer
  selector:
    app: spring-users
  ports:
    - port: 9092
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-users-deployment
  labels:
    app: spring-users
spec:
  selector:
    matchLabels:
      app: spring-users
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: spring-users
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: spring-users-container
          image: rheadash/spring-users:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
