apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: users
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /users
        backend:
          serviceName: users
          servicePort: 8082
