apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: books
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /books
        backend:
          serviceName: books
          servicePort: 8083
