INSERT INTO books (isbn, title, author, description, price, stock) VALUES
('1338790234', 'The Christmas Pig', 'J.K. Rowling', 'Adventure about one child''s love for his most treasured thing, and how far he will go to find it. A tale for the whole family to fall in love with. One boy and his toy are about to change everything.', 21.99, 10),
('1419749153', 'Diary of a Wimpy Kid', 'Jeff Kinney', 'After a disastrous field day competition at school, Greg decides that when it comes to his athletic career, he''s officially retired. But after his mom urges him to give sports one more chance.', 13.87, 10),
('0786967293', 'Fizban''s Treasury of Dragons', 'Wizards RPG Team', 'Unlikely war hero, divine avatar of a dragon-god--and your guide to the mysteries of dragonkind. What is the difference between a red dragon and a gold dragon?', 41.97, 10),
('B009MSFXRQ', 'The Hobbit or There and Back Again', 'J.R.R. Tolkien', 'A glorious account of a magnificent adventure, filled with suspense and seasoned with a quiet humor that is irresistible. A fine adventurous tale.', 3.59, 10),
('1913484106', 'Guinness World Records 2022', 'Unknown', 'Guinness World Records 2022 provides a fascinating snapshot of our world today. Our editors have chosen to curate the book with environmental issues at the forefront of their mind.', 25.29, 10),
('0767902890', 'The Things They Carried', 'Tim O''Brien', 'A collection of interrelated short pieces which ultimately reads with the dramatic force and tension of a novel. Yet each one of the twenty-two short pieces is written with such.', 4.69, 10),
('0307454541', 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Harriet Vanger, a scion of one of Sweden''s wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth.', 4.69, 10),
('0060256702', 'The Giving Tree', 'Shel Silverstein', 'The Giving Tree, a story of unforgettable perception, beautifully written and illustrated by the gifted and versatile Shel Silverstein, has been a classic favorite for generations. The gift of giving.', 30.89, 10),
('1984877925', 'Will', 'Mark Manson and Will Smith', 'One of the most dynamic and globally recognized entertainment forces of our time opens up fully about his life, in a brave and inspiring book that traces his learning curve to.', 26.05, 10),
('0439906652', 'Llama Llama Red Pajama', 'Anna Dewdney', 'A summer of green apple trees, mowed lawns, and new sneakers. Of half-burnt firecrackers, of gathering dandelions. It was a summer of sorrows and marvels.', 26.05, 10);