#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  creationTimestamp: null
#  labels:
#    io.kompose.service: rabbitmq
#  name: rabbitmq
#spec:
#  replicas: 1
#  strategy: {}
#  selector:
#    matchLabels:
#      name: rabbitmq
#  template:
#    metadata:
#      creationTimestamp: null
#      labels:
#        name: rabbitmq
#    spec:
#      containers:
#      - image: rabbitmq:3-management
#        imagePullPolicy: Always
#        name: rabbitmq
#        ports:
#        - containerPort: 8088
#        resources: {}
#      restartPolicy: Always
#status: {}


apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
    - image: rabbitmq:management
      name: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 4369
        - containerPort: 15672
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}