#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yaml
#    kompose.version: 1.17.0 (a74acad)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: rabbitmq
#  name: rabbitmq
#spec:
#  ports:
#  - name: "8088"
#    port: 8088
#    targetPort: 8088
#  type: LoadBalancer
#  selector:
#    name: rabbitmq
#status:
#  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}

#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yaml
#    kompose.version: 1.17.0 (a74acad)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: rabbitmq
#  name: rabbitmq
#spec:
#  ports:
#    - port: 15672
#      protocol: TCP
#      targetPort: 15672
#  type: LoadBalancer
#  selector:
#    app: rabbitmq
#status:
#  loadBalancer: {}