apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-strip-path
route:
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  strip_path: true

# kubectl patch ingress backoffice-api -p '{"metadata":{"annotations":{"konghq.com/override":"kong-strip-path"}}}'
